# this is service-zuul

spring:
  application:
    name: ${service.name.zuul}
  cloud:
    config:
      name: neo-config
      label: master
      profile: dev
      discovery:
        enabled: true
        serviceId: config-server
    
server:
  port: ${service.port.zuul}
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: ${service.name.ribbon}
    api-b:
      path: /api-b/**
      serviceId: ${service.name.feign}
