# this is service-zuul

spring:
  application:
    name: service-zuul
    
server:
  port: 10001
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign
