# this is demo project

spring:
  application:
    name: ${service.name.hi}
  cloud:
    config:
      name: neo-config
      label: master
      profile: dev
      discovery:
        enabled: true
        serviceId: config-server
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 
    pool.max-active: 8
    pool.max-wait: -1
    pool.max-idle: 8
    pool.min-idle: 0
    timeout: 2000
# mvc:
#   view:
#     prefix: /WEB-INF/jsp/
#     suffix: .jsp
    
server:
  port: ${service.port.hi}
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka
#   instance:
#     preferIpAddress: true

logging:
  level:
    org.springframework.web: DEBUG
    demo.test.mapper: DEBUG
    demo.tool.mapper: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "[%p] [%d{yyyy-MM-dd HH:mm:ss}][%c]%m%n [%thread] %-5level %logger{36}"
      
  file: /home/u1/logs/ssms.log