envName: dev
neo.hello: hello im dev update 
testValue: testValue init

service:
  name:
    hi: hi-service
    config: config-service
    gateway: gateway
    ribbon: ribbon-service
    feign: feign-service
    zuul: zuul-service
    finance: finance-service
    image: image-service

  port:
    hi: 20019
    config: 8888
    gateway: 20001
    ribbon: 20012
    feign: 20013
    zuul: 20014
    finance: 20020
    image: 20021

rabbitmq: 
  host: 45.76.205.204
  port: 5672
  username: u1
  password: something