neo.hello: hello im dev update 
testValue: testValue init

service:
  name:
    hi: hi-service
    config: config-service
    ribbon: ribbon-service
    feign: feign-service
    zuul: zuul-service
    finance: finance-service
    image: image-service

  port:
    hi: 20020
    config: 8888
    ribbon: 20012
    feign: 20013
    zuul: 20014
    finance: 20020
    image: 20021
