# this is service-ribbon

spring:
  application:
    name: ${service.name.ribbon}
  cloud:
    config:
      name: neo-config
      label: master
      profile: dev
      discovery:
        enabled: true
        serviceId: config-server
server:
  port: ${service.port.ribbon}
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka
