# this is service-feign

spring:
  application:
    name: service-feign
    
server:
  port: 8766
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

feign.hystrix.enabled: true