# this is service-feign

spring:
  application:
    name: ${service.name.feign}
  cloud:
    config:
      name: neo-config
      label: master
      profile: dev
      discovery:
        enabled: true
        serviceId: config-server
    
server:
  port: ${service.port.feign}
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka

feign.hystrix.enabled: true