# this is service-feign

envName: dev
branchName: dev

spring:
  application:
    name: ${service.name.feign}
  cloud:
    config:
      failFast: true
      name: config-file
      label: ${branchName}
      profile: ${envName}
      discovery:
        enabled: true
        serviceId: config-service
    
server:
  port: ${service.port.feign}
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka

feign.hystrix.enabled: true

testValueInFeign: ${testValue}