# this is config-server

spring:
  application:
    name: config-service
  cloud:
    config:
      label: master
      server:
        git:
          # 可配置远程/本地仓库 
          # uri: https://github.com/a39676/scProjectPack/
          uri: D:/scProjectPack
          searchPaths: configFolder
          username:
          password:
    
server:
  port: 8888
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka
