# this is config-server

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/a39676/scProjectPack/
          searchPaths: configFolder
          username:
          password:
    
server:
  port: 8888
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
