# this is config-client

server:
  port: 19999
  
spring:
  application:
    name: config-client
  cloud:
    config:
      failFast: true
      # uri: http://localhost:8888 # 未经过eureka server --> 直连时, 配置configuration server 访问地址
      name: neo-config
      label: master
      profile: dev
      discovery:
        enabled: true
        serviceId: config-service
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka

