# this is config-client

server:
  port: 8881
  
spring:
  application:
    name: config-client
  cloud:
    config:
      # uri: http://localhost:8888 # 未经过eureka server --> 直连时, 配置configuration server 访问地址
      name: neo-config
      label: master
      profile: dev
      discovery:
        enabled: true
        serviceId: config-server
    bus:
      enabled: true
      trace:
        enabled: true
  # rabbitmq: # 2019-05-09 待重新部署 rabbitMQ
    # host: localhost
    # port: 5672
    # username: guest
    # password: guest

management:
  endpoints:
    web:
      exposure:
        include: '*' 
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka