# this is config-client

server:
  port: 8881
  
spring:
  application:
    name: config-client
  cloud:
    config:
      # uri: http://localhost:8888
      name: neo-config
      label: master
      profile: dev
      discovery:
        enabled: true
        serviceId: config-server
    bus:
      enabled: true
      trace:
        enabled: true
  # rabbitmq:
    # host: localhost
    # port: 5672
    # username: guest
    # password: guest

management:
  endpoints:
    web:
      exposure:
        include: '*'
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka