# this is config-client

server:
  port: 8881
  
spring:
  application:
    name: config-client
  cloud:
    config:
      uri: http://localhost:8888
      name: neo-config
      label: master
      profile: dev
    
  