# this is config-client

server:
  port: 19999
  
spring:
  application:
    name: config-client
  cloud:
    config:
      # uri: http://localhost:8888 # 未经过eureka server --> 直连时, 配置configuration server 访问地址
      name: neo-config
      label: master
      profile: dev
      discovery:
        enabled: true
        serviceId: config-server
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 45.76.205.204
    port: 5672
    username: u1
    password: something

management:
  endpoints:
    web:
      exposure:
        include: '*' 
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka

testValue: ${testValue}